/**
 * Copyright (c) 2020, ETH Zurich, Computer Engineering Group
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * basic GPIO actuation
 *
 * usage:
 *          ./fl_act [starttime] [stoptime/duration]
 *
 * starttime          UNIX timestamp of the sampling start
 * stoptime/duration  UNIX timestamp of the sampling stop, or sampling duration in seconds
 *
 */

// INCLUDES
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <signal.h>
#include <time.h>
#include <unistd.h>


// DEFINES

#define GPIO_PATH             "/sys/class/gpio/gpio"
#define GPIO_nRST             77
#define GPIO_nRST_DESIGNATOR  "P840"


// GLOBALS

static bool  running = true;


// FUNCTIONS

static void sig_handler(int sig_num)
{
  // signal generated by stop function
  if (sig_num == SIGTERM) {
    running = false;
  }

  // signal generated by interactive user (ctrl+C)
  if (sig_num == SIGINT) {
    running = false;
  }
}


int register_sighandler(void)
{
  struct sigaction signal_action;
  signal_action.sa_handler = sig_handler;
  sigemptyset(&signal_action.sa_mask);
  signal_action.sa_flags = 0;
  if (sigaction(SIGTERM, &signal_action, NULL) < 0 ||
      sigaction(SIGINT, &signal_action, NULL) < 0) {
    return 1;
  }
  return 0;
}


int reset_act(unsigned long starttime, unsigned long stoptime)
{
  FILE* freset = NULL;
  unsigned long currtime = time(NULL);
  char buffer[256];

  if (!starttime || stoptime < starttime || !currtime) {
    return 1;
  }

  // make sure the reset pin is configured as output
  system("config-pin -a " GPIO_nRST_DESIGNATOR " out");

  sprintf(buffer, GPIO_PATH "%d/value", GPIO_nRST);


  while ((currtime < (starttime - 1)) && running) {
    // alternatively, use clock_gettime(CLOCK_REALTIME, &currtime)
    currtime = time(NULL);
    usleep(500000);
  }
  freset = fopen(buffer, "w");
  if (!freset) {
    return 2;
  }
  while ((currtime < starttime) && running) {
    // alternatively, use clock_gettime(CLOCK_REALTIME, &currtime)
    currtime = time(NULL);
    usleep(100);
  }
  // release reset
  fwrite("1", 1, 1, freset);
  fclose(freset);

  // wait for test stop
  while ((currtime < (stoptime - 1)) && running) {
    // alternatively, use clock_gettime(CLOCK_REALTIME, &currtime)
    currtime = time(NULL);
    usleep(500000);
  }
  freset = fopen(buffer, "w");
  if (!freset) {
    return 2;
  }
  while ((currtime < stoptime) && running) {
    // alternatively, use clock_gettime(CLOCK_REALTIME, &currtime)
    currtime = time(NULL);
    usleep(100);
  }
  // put target in reset state
  fwrite("0", 1, 1, freset);
  fclose(freset);

  return 0;
}


// MAIN
int main(int argc, char** argv)
{
  long int starttime = 0;
  long int stoptime  = 0;

  // --- check arguments ---
  if (argc < 3) {
    printf("not enough arguments supplied\n");
    return 1;
  }
  starttime = strtol(argv[1], NULL, 10);
  if (starttime < time(NULL)) {
    starttime = time(NULL) + 2;    // invalid start time -> start in 2 seconds
  }
  stoptime = strtol(argv[2], NULL, 10);
  if (stoptime < starttime) {
    // appears to be an offset rather than a UNIX timestamp
    stoptime += starttime;
  }

  // --- register signal handler ---
  if (register_sighandler() != 0) {
    return 1;
  }

  // --- start actuation ---
  return reset_act(starttime, stoptime);
}
